name: "MUTS-CI-Action"
description: "Runs the mutation testing framework on a target C++ project"
inputs:
  project-path:
    description: "Path to the project root"
    required: true
  pr-assignees-json: # New input defined here
    description: "JSON array of pull request assignee usernames (logins)"
    required: false # Set to false in case the action is used outside a PR context
runs:
  using: "composite"
  steps:

    - name: Get Assignee Details and Set Environment Variable
      uses: actions/github-script@v7
      id: format_authors
      env:
        PR_ASSIGNEES_JSON: ${{ inputs.pr-assignees-json }}
      with:
        github-token: ${{ github.token }}
        script: |
          const script = require('${{ github.action_path }}/get-pull-request-info.js');
          await script({github, context, core});


    - name: "Run MUTS-Git"
      uses: "docker://ekrogh18/muts-git:0.2.0"

    - name: Show result of MUTS-Git
      shell: bash
      run: |
        cat git-commits.json
    
    - name: Run MUTS-CI
      uses: "docker://ekrogh18/muts-ci:0.2.0_old_urindev"
      env:
        # The variable is now available as a regular environment variable
        TARGET_AUTHORS: ${{ env.TARGET_AUTHORS }} 
      continue-on-error: true