name: "MUTS-CI-Action"
description: "Runs the mutation testing framework on a target C++ project"
inputs:
  project-path:
    description: "Path to the project root"
    required: true
runs:
  using: "composite"
  steps:

    - name: Get Pull Request Authors and Set Environment Variable
      uses: actions/github-script@v7
      id: get_pr_authors
      with:
        github-token: ${{ github.token }}
        script: |
          const script = require('${{ github.action_path }}/get-pull-request-info.js');
          await script({github, context, core});


    - name: "Run MUTS-Git"
      uses: "docker://ekrogh18/muts-git:0.2.1"

    - name: Show result of MUTS-Git
      shell: bash
      run: |
        cat git-commits.json

    - name: "Run MUTS-CI image to get MUTS-CI binary"
      uses: "docker://ekrogh18/muts-ci:0.2.2"

    - name: debug
      shell: bash
      run: |
        ls -la .
        cd cppcheck
        ls -la .
    - name: Run MUTS-CI
      run: |
        docker run --rm \
          -e TARGET_AUTHORS="${TARGET_AUTHORS}" \
          -e TARGET_COMMIT_COUNT="${TARGET_COMMIT_COUNT}" \
          "$TARGET_PROJECT_IMAGE"

    # - name: Run MUTS-CI
    #   shell: bash
    #   env:
    #     TARGET_AUTHORS: ${{ env.TARGET_AUTHORS }}
    #     TARGET_COMMIT_COUNT: ${{ env.TARGET_COMMIT_COUNT }}
    #   continue-on-error: true
    #   run: |
    #     cd $GITHUB_WORKSPACE/${TARGET_LEAF}
    #     exe="./MUTS-CI"
    #     if [ ! -x "$exe" ]; then
    #       chmod +x "$exe" || true
    #     fi
    #     "$exe" --file-list-json=$GITHUB_WORKSPACE/git-commits.json