name: "MUTS-CI-Action"
description: "Runs the mutation testing framework on a target C++ project"

inputs:
  project-path:
    description: "Path to the project root"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run MUTS-Git"
      uses: "docker://ekrogh18/muts-git:0.1.5"

    - name: Show results of MUTS-Git
      shell: bash
      run: |
        cat "${{ inputs.project-path }}/git-commits.json"
    
    - name: "Run MUTS-CI executable"
      shell: bash
      run: |
        chmod +x "${GITHUB_ACTION_PATH}/MUTS-CI"
        "${GITHUB_ACTION_PATH}/MUTS-CI" --file-list-json="${{ inputs.project-path }}/files.json" | tee temp-log.txt
    
    - name: Show results of MUTS-CI
      shell: bash
      run: |
        cat temp-log.txt