name: "MUTS-CI-Action"
description: "Runs the mutation testing framework on a target C++ project"

inputs:
  project-path:
    description: "Path to the project root"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run MUTS-Git"
      uses: "docker://ekrogh18/muts-git:0.1.5"
    
    - name: "Run MUTS-CI executable"
      shell: bash
      run: |
        bash "${GITHUB_ACTION_PATH}/main.sh" --file-list-json="${{ inputs.project-path }}/files.json"