name: "MUTS-CI-Action"
description: "Runs the mutation testing framework on a target C++ project"

inputs:
  project-path:
    description: "Path to the project root"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Run MUTS-Git"
      uses: "docker://ekrogh18/muts-git:0.1.5"