name: "MUTS-CI-Action"
description: "Runs the mutation testing framework on a target C++ project"
inputs:
  project-path:
    description: "Path to the project root"
    required: true
  pr-assignees-json: # New input defined here
    description: "JSON array of pull request assignee usernames (logins)"
    required: false # Set to false in case the action is used outside a PR context
runs:
  using: "composite"
  steps:

    - name: Get Assignee Details and Set Environment Variable
      uses: actions/github-script@v7
      id: format_authors
      with:
        github-token: ${{ github.token }}
        script: |
          const assigneesJson = `${{ inputs.pr-assignees-json }}`;
          const assignees = JSON.parse(assigneesJson || '[]');
          
          let targetAuthors = [];
          
          for (const login of assignees) {
            // 1. Fetch user details from the GitHub API
            const { data: user } = await github.rest.users.getByUsername({
              username: login
            });

            // 2. Determine the name and email
            // Use the user's name or login, and a reliable email address.
            const name = user.name || login;
            const email = user.email || `${login}@users.noreply.github.com`;
            
            // 3. Format the string for the environment variable, e.g., 'John <john@email.com>'
            targetAuthors.push(`${name} <${email}>`);
          }

          // **FIX 1: Format as a single string, not a JSON array**
          // Output: 'John <john@email.com>, Eva <eva@email.com>'
          const authorsListString = targetAuthors.join(', ');
          // Final desired export format: '[John <john@email.com>, Eva <eva@email.com>]'
          const envVarValue = `[${authorsListString}]`;

          // 4. Export the environment variable for subsequent steps
          console.log(`Setting TARGET_AUTHORS to: ${envVarValue}`);
          
          // **FIX 2: Use core.exportVariable for reliable export**
          core.exportVariable('TARGET_AUTHORS', envVarValue);


    - name: "Run MUTS-Git"
      uses: "docker://ekrogh18/muts-git:0.2.0"

    - name: Show result of MUTS-Git
      shell: bash
      run: |
        cat git-commits.json
    
    - name: Run MUTS-CI
      uses: "docker://ekrogh18/muts-ci:0.2.0_old_urindev"
      env:
        # The variable is now available as a regular environment variable
        TARGET_AUTHORS: ${{ env.TARGET_AUTHORS }} 
      continue-on-error: true